services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:v0.18.1
    ports: 
       - 19100:9100/tcp
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --web.listen-address=0.0.0.0:9100
    volumes:
       - /proc:/host/proc:ro
       - /sys:/host/sys:ro
  db:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: timescale/pg_prometheus:latest-pg11
    ports:
    - 5432:5432/tcp
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090/tcp
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  prometheus_postgresql_adapter:
    image: timescale/prometheus-postgresql-adapter:latest
    depends_on:
    - db
    - prometheus
    environment:
      TS_PROM_LOG_LEVEL: debug
      TS_PROM_PG_DB_CONNECT_RETRIES: 10
      TS_PROM_PG_HOST: db
      TS_PROM_PG_PASSWORD: postgres
      TS_PROM_PG_SCHEMA: postgres
      TS_PROM_WEB_TELEMETRY_PATH: /metrics-text
    image: timescale/prometheus-postgresql-adapter:latest
    ports:
    - 9201:9201/tcp
  pgweb:
    image: sosedoff/pgweb:latest
    restart: always
    ports:
    - 8081:8081/tcp
    links:
    - db:db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    depends_on:
    - db
version: '3.0'
